"""Map heterogeneous-catalyst compositions to Materials Project bulk structures.

Each returned record is a *database reference* (MP material id + summary fields),
not a structure generated by the CVAE. Multi-element candidates typically yield
several references (e.g. unary metal + binary oxide).
"""

from __future__ import annotations

import json
import logging
import os
import re
from dataclasses import asdict, dataclass
from typing import Any, Iterable

from urllib.parse import quote

from .materials_project import OFFLINE_MP_SEED

logger = logging.getLogger(__name__)

MP_MATERIAL_URL = "https://next-gen.materialsproject.org/materials/{material_id}"


def _patch_typing_for_mp_api() -> None:
    """Let newer emmet-core/mp-api releases import on Python 3.10."""
    import typing

    os.environ.setdefault("MPLCONFIGDIR", "/private/tmp")
    if hasattr(typing, "NotRequired"):
        return
    try:
        from typing_extensions import NotRequired
    except Exception:
        return
    typing.NotRequired = NotRequired  # type: ignore[attr-defined]


def mp_crystal_structure_page_url(material_id: str, formula_hint: str | None = None) -> str:
    """Deep link to MP next-gen **Crystal structure** panel (same pattern as the live site)."""
    fp = (formula_hint or "").strip()
    if "(" in fp:
        fp = fp.split("(", 1)[0].strip()
    parts = fp.split()
    formula_q = parts[0] if parts else ""
    if not formula_q:
        formula_q = material_id
    return (
        f"https://next-gen.materialsproject.org/materials/{material_id}"
        f"?formula={quote(formula_q, safe='')}#crystal_structure"
    )


@dataclass(frozen=True)
class BulkStructureRef:
    chemsys: str
    material_id: str
    formula_pretty: str
    spacegroup: str | None
    energy_above_hull: float | None
    formation_energy_per_atom_ev: float | None
    source: str  # "mp_api" | "offline_seed"

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["mp_url"] = MP_MATERIAL_URL.format(material_id=self.material_id)
        d["mp_crystal_url"] = mp_crystal_structure_page_url(self.material_id, self.formula_pretty)
        return d


def normalize_chemsys(chemsys: str) -> str:
    parts = [p for p in chemsys.replace("\u2013", "-").split("-") if p.strip()]
    return "-".join(sorted(parts))


def chemsys_fragments(elements: Iterable[str]) -> list[str]:
    """Build MP chemsys strings: unaries, element-oxygen binaries, and full system."""
    elems = sorted({str(e).strip() for e in elements if str(e).strip()})
    out: list[str] = []
    seen: set[str] = set()

    def add(cs: str) -> None:
        n = normalize_chemsys(cs)
        if n and n not in seen:
            seen.add(n)
            out.append(n)

    for e in elems:
        add(e)
    if "O" in elems:
        for e in elems:
            if e != "O":
                add("-".join(sorted([e, "O"])))
    if 2 <= len(elems) <= 5:
        add("-".join(elems))
    return out


def _offline_by_chemsys() -> dict[str, BulkStructureRef]:
    out: dict[str, BulkStructureRef] = {}
    for ent in OFFLINE_MP_SEED:
        key = normalize_chemsys("-".join(ent.composition))
        sym = str(ent.properties.get("structure", "") or "")
        out[key] = BulkStructureRef(
            chemsys=key,
            material_id=ent.identifier,
            formula_pretty=ent.name,
            spacegroup=sym or None,
            energy_above_hull=None,
            formation_energy_per_atom_ev=float(ent.properties.get("formation_energy_per_atom_ev") or 0.0),
            source="offline_seed",
        )
    return out


_OFFLINE = _offline_by_chemsys()
_OFFLINE.setdefault(
    "O-Ti",
    BulkStructureRef(
        chemsys="O-Ti",
        material_id="mp-390",
        formula_pretty="TiO2",
        spacegroup=None,
        energy_above_hull=None,
        formation_energy_per_atom_ev=None,
        source="offline_seed",
    ),
)


def _live_pick_best(chemsys: str) -> BulkStructureRef | None:
    api_key = (os.environ.get("MP_API_KEY") or "").strip()
    if not api_key:
        return None
    try:
        _patch_typing_for_mp_api()
        from mp_api.client import MPRester  # type: ignore
    except Exception as exc:
        logger.info("mp-api not importable (%s); offline MP only for lattices.", exc)
        return None

    try:
        with MPRester(api_key) as mpr:
            docs = list(
                mpr.summary.search(
                    chemsys=chemsys,
                    fields=[
                        "material_id",
                        "formula_pretty",
                        "symmetry",
                        "energy_above_hull",
                        "formation_energy_per_atom",
                    ],
                )
            )
    except Exception as exc:
        logger.warning("MP summary.search failed for chemsys=%s: %s", chemsys, exc)
        return None

    if not docs:
        return None

    def hull_key(d: Any) -> float:
        h = getattr(d, "energy_above_hull", None)
        try:
            return float(h) if h is not None else float("inf")
        except (TypeError, ValueError):
            return float("inf")

    docs.sort(key=hull_key)
    best = docs[0]
    sym = getattr(getattr(best, "symmetry", None), "symbol", None)
    h = getattr(best, "energy_above_hull", None)
    fe = getattr(best, "formation_energy_per_atom", None)
    try:
        h_f = float(h) if h is not None else None
    except (TypeError, ValueError):
        h_f = None
    try:
        fe_f = float(fe) if fe is not None else None
    except (TypeError, ValueError):
        fe_f = None

    return BulkStructureRef(
        chemsys=normalize_chemsys(chemsys),
        material_id=str(best.material_id),
        formula_pretty=str(getattr(best, "formula_pretty", "") or best.material_id),
        spacegroup=str(sym) if sym else None,
        energy_above_hull=h_f,
        formation_energy_per_atom_ev=fe_f,
        source="mp_api",
    )


def resolve_bulk_refs_for_elements(elements: list[str]) -> list[dict[str, Any]]:
    """Return unique MP bulk references for elemental components (pipe or list)."""
    frags = chemsys_fragments(elements)
    seen_ids: set[str] = set()
    rows: list[dict[str, Any]] = []

    for frag in frags:
        ref: BulkStructureRef | None = None
        live = _live_pick_best(frag)
        if live is not None:
            ref = live
        else:
            key = normalize_chemsys(frag)
            ref = _OFFLINE.get(key)
        if ref is None:
            continue
        if ref.material_id in seen_ids:
            continue
        seen_ids.add(ref.material_id)
        rows.append(ref.to_dict())
    return rows


def summary_line(refs: list[dict[str, Any]], *, max_len: int = 220) -> str:
    if not refs:
        return ""
    parts = [f"{r.get('formula_pretty', r['material_id'])} ({r['material_id']})" for r in refs]
    text = "; ".join(parts)
    return text if len(text) <= max_len else text[: max_len - 3] + "..."


def attach_columns_for_dataframe(rows: list[list[str]]) -> tuple[list[str], list[str]]:
    """Given per-row element lists, return parallel JSON summaries and human summaries."""
    json_cols: list[str] = []
    summary_cols: list[str] = []
    for elems in rows:
        refs = resolve_bulk_refs_for_elements(elems)
        json_cols.append(json.dumps(refs, separators=(",", ":")))
        summary_cols.append(summary_line(refs))
    return json_cols, summary_cols


def _elements_from_formula_text(text: str) -> list[str]:
    """Extract element symbols from display formulas such as `Pd/TiO2/ZnO`."""
    elems: list[str] = []
    for symbol in re.findall(r"[A-Z][a-z]?", str(text)):
        if symbol not in elems:
            elems.append(symbol)
    return elems


def mp_refs_from_clean_csv_row(row: Any) -> list[dict[str, Any]]:
    """Use `mp_structure_refs` when present; otherwise resolve from `components` / `composition_view`."""
    refs: list[dict[str, Any]] = []
    raw = row.get("mp_structure_refs")
    if isinstance(raw, str) and raw.strip().startswith("["):
        try:
            parsed = json.loads(raw)
            if isinstance(parsed, list):
                refs = [r for r in parsed if isinstance(r, dict)]
        except json.JSONDecodeError:
            pass
    elems: list[str] = []
    c = row.get("components")
    if isinstance(c, str) and c.strip():
        elems = [x for x in c.split("|") if x.strip()]
    for symbol in _elements_from_formula_text(str(row.get("composition_view", ""))):
        if symbol not in elems:
            elems.append(symbol)
    if not elems:
        return refs

    seen_ids = {str(r.get("material_id", "")) for r in refs}
    for ref in resolve_bulk_refs_for_elements(elems):
        mid = str(ref.get("material_id", ""))
        if mid and mid not in seen_ids:
            refs.append(ref)
            seen_ids.add(mid)
    return refs
